#include "wren_backend.h"
#ifdef WREC_WITH_WREN
#include "wren.h"
#include <stdio.h>
#include <string.h>
#include "../src/runtime_adapter.h"
static WrenVM *vm;
static irc_output_sink wrec_sink;
static WrenHandle *hello_call; static WrenHandle *event_call;
#define WREC_TIMER_NAME_MAX 64
typedef struct { char name[WREC_TIMER_NAME_MAX]; bot_timer_id id; int active; } wrec_timer_context;
static wrec_timer_context timer_contexts[BOT_MAX_TIMERS];
#define WREC_EVENT_NAME_MAX 64
typedef struct {char name[WREC_EVENT_NAME_MAX]; char handler[WREC_EVENT_NAME_MAX]; int active;} wrec_event_binding;
static wrec_event_binding event_bindings[8];
#define WREC_COMMAND_MAX 32
static wrec_event_binding command_bindings[WREC_COMMAND_MAX];
static irc_event active_event;
static int active_event_valid;
static int wren_command_on(const char *name,const char *handler){size_t i;if(!name||!handler||strlen(name)>=WREC_EVENT_NAME_MAX||strlen(handler)>=WREC_EVENT_NAME_MAX)return 0;for(i=0;i<WREC_COMMAND_MAX;i++)if(!command_bindings[i].active||strcmp(command_bindings[i].name,name)==0){snprintf(command_bindings[i].name,sizeof(command_bindings[i].name),"%s",name);snprintf(command_bindings[i].handler,sizeof(command_bindings[i].handler),"%s",handler);command_bindings[i].active=1;return 1;}return 0;}
static int wren_event_on(const char *name,const char *handler){size_t i;if(!name||!handler||strlen(name)>=WREC_EVENT_NAME_MAX||strlen(handler)>=WREC_EVENT_NAME_MAX)return 0;for(i=0;i<8;i++)if(!event_bindings[i].active||strcmp(event_bindings[i].name,name)==0){snprintf(event_bindings[i].name,sizeof(event_bindings[i].name),"%s",name);snprintf(event_bindings[i].handler,sizeof(event_bindings[i].handler),"%s",handler);event_bindings[i].active=1;return 1;}return 0;}

void wren_backend_set_output_sink(const irc_output_sink *sink){if(sink)wrec_sink=*sink;else memset(&wrec_sink,0,sizeof(wrec_sink));}
static void foreign_say(WrenVM *v){const char *t,*x;wrenEnsureSlots(v,2);t=wrenGetSlotString(v,0);x=wrenGetSlotString(v,1);wrenSetSlotBool(v,0,irc_send_privmsg(&wrec_sink,t,x));}
static void foreign_notice(WrenVM *v){const char *t,*x;wrenEnsureSlots(v,2);t=wrenGetSlotString(v,0);x=wrenGetSlotString(v,1);wrenSetSlotBool(v,0,irc_send_notice(&wrec_sink,t,x));}
static void foreign_join(WrenVM *v){const char *c;wrenEnsureSlots(v,1);c=wrenGetSlotString(v,0);wrenSetSlotBool(v,0,irc_send_join(&wrec_sink,c));}
static void foreign_part(WrenVM *v){const char *c,*r;wrenEnsureSlots(v,2);c=wrenGetSlotString(v,0);r=wrenGetSlotString(v,1);wrenSetSlotBool(v,0,irc_send_part(&wrec_sink,c,r));}
static int valid_timer_name(const char *s){size_t i;if(!s||!*s)return 0;for(i=0;s[i];++i)if(!((s[i]>='A'&&s[i]<='Z')||(s[i]>='a'&&s[i]<='z')||(s[i]>='0'&&s[i]<='9')||s[i]=='_'))return 0;return i<WREC_TIMER_NAME_MAX;}
static int wren_timer_dispatch(bot_timer_id id,void *user){wrec_timer_context *ctx=(wrec_timer_context *)user;WrenHandle *call;WrenInterpretResult rc;if(!vm||!ctx||!ctx->active||!valid_timer_name(ctx->name))return -1;wrenEnsureSlots(vm,1);wrenGetVariable(vm,"bot","Bot",0);call=wrenMakeCallHandle(vm,ctx->name);if(!call)return -1;rc=wrenCall(vm,call);wrenReleaseHandle(vm,call);(void)id;return rc==WREN_RESULT_SUCCESS?0:-1;}
static bot_timer_id wrec_named_timer(uint64_t delay,uint64_t interval,int repeat,const char *name){size_t i;bot_timer_id id;wrec_timer_context *ctx=NULL;if(!valid_timer_name(name))return 0;for(i=0;i<BOT_MAX_TIMERS;i++)if(!timer_contexts[i].active){ctx=&timer_contexts[i];break;}if(!ctx)return 0;memset(ctx,0,sizeof(*ctx));snprintf(ctx->name,sizeof(ctx->name),"%s",name);ctx->active=1;id=repeat?wrec_runtime_timer_every(interval,wren_timer_dispatch,ctx):wrec_runtime_timer_after(delay,wren_timer_dispatch,ctx);if(!id){ctx->active=0;return 0;}ctx->id=id;return id;}
static void foreign_context_nick(WrenVM *v){wrenEnsureSlots(v,1);wrenSetSlotString(v,0,active_event_valid?active_event.nick:"");}
static void foreign_context_target(WrenVM *v){wrenEnsureSlots(v,1);wrenSetSlotString(v,0,active_event_valid?active_event.target:"");}
static void foreign_context_text(WrenVM *v){wrenEnsureSlots(v,1);wrenSetSlotString(v,0,active_event_valid?active_event.text:"");}
static void foreign_context_command(WrenVM *v){wrenEnsureSlots(v,1);wrenSetSlotString(v,0,active_event_valid?active_event.command:"");}
static void foreign_context_args(WrenVM *v){wrenEnsureSlots(v,1);wrenSetSlotString(v,0,active_event_valid?active_event.args:"");}
static void foreign_command_on(WrenVM *v){const char *name,*handler;wrenEnsureSlots(v,2);name=wrenGetSlotString(v,0);handler=wrenGetSlotString(v,1);wrenSetSlotBool(v,0,wren_command_on(name,handler));}
static void foreign_event_on(WrenVM *v){const char *name,*handler;wrenEnsureSlots(v,2);name=wrenGetSlotString(v,0);handler=wrenGetSlotString(v,1);wrenSetSlotBool(v,0,wren_event_on(name,handler));}
static void foreign_timer_after(WrenVM *v){const char *name;double ms;bot_timer_id id;wrenEnsureSlots(v,2);ms=wrenGetSlotDouble(v,0);name=wrenGetSlotString(v,1);id=(ms>=0&&name)?wrec_named_timer((uint64_t)ms,0,0,name):0;wrenSetSlotDouble(v,0,(double)id);}
static void foreign_timer_every(WrenVM *v){const char *name;double ms;bot_timer_id id;wrenEnsureSlots(v,2);ms=wrenGetSlotDouble(v,0);name=wrenGetSlotString(v,1);id=(ms>0&&name)?wrec_named_timer((uint64_t)ms,(uint64_t)ms,1,name):0;wrenSetSlotDouble(v,0,(double)id);}
static void foreign_timer_cancel(WrenVM *v){double value;bot_timer_id id;size_t i;int ok=0;wrenEnsureSlots(v,1);value=wrenGetSlotDouble(v,0);id=(bot_timer_id)value;if(id&&wrec_runtime_timer_cancel(id)){for(i=0;i<BOT_MAX_TIMERS;i++)if(timer_contexts[i].active&&timer_contexts[i].id==id){timer_contexts[i].active=0;break;}ok=1;}wrenSetSlotBool(v,0,ok);}
static WrenForeignMethodFn bind_foreign(const char *module,const char *class_name,bool is_static,const char *signature){(void)is_static;if(strcmp(module,"bot")!=0)return NULL;if(strcmp(class_name,"IRCContext")==0){if(strcmp(signature,"nick()")==0)return foreign_context_nick;if(strcmp(signature,"target()")==0)return foreign_context_target;if(strcmp(signature,"text()")==0)return foreign_context_text;if(strcmp(signature,"command()")==0)return foreign_context_command;if(strcmp(signature,"args()")==0)return foreign_context_args;return NULL;}if(strcmp(class_name,"Commands")==0){if(strcmp(signature,"on(_,_)")==0)return foreign_command_on;return NULL;}if(strcmp(class_name,"Events")==0){if(strcmp(signature,"on(_,_)")==0)return foreign_event_on;return NULL;}if(strcmp(class_name,"Timer")==0){if(strcmp(signature,"after(_,_)")==0)return foreign_timer_after;if(strcmp(signature,"every(_,_)")==0)return foreign_timer_every;if(strcmp(signature,"cancel(_)")==0)return foreign_timer_cancel;return NULL;}if(strcmp(class_name,"IRC")!=0)return NULL;if(strcmp(signature,"say(_,_)")==0)return foreign_say;if(strcmp(signature,"notice(_,_)")==0)return foreign_notice;if(strcmp(signature,"join(_)")==0)return foreign_join;if(strcmp(signature,"part(_,_)")==0)return foreign_part;if(strcmp(module,"bot")==0&&strcmp(class_name,"Timer")==0){if(strcmp(signature,"after(_,_)")==0)return foreign_timer_after;if(strcmp(signature,"every(_,_)")==0)return foreign_timer_every;if(strcmp(signature,"cancel(_)")==0)return foreign_timer_cancel;}return NULL;}
int wren_backend_eval(const char *source){if(!vm||!source)return -1;return wrenInterpret(vm,"bot-eval",source)==WREN_RESULT_SUCCESS?0:-1;}
static const char *bootstrap="foreign class IRC { static say(target, text) {} static notice(target, text) {} static join(channel) {} static part(channel, reason) {} } foreign class Timer { static after(ms, handler) {} static every(ms, handler) {} static cancel(id) {} } foreign class Events { static on(name, handler) {} } foreign class Commands { static on(name, handler) {} } foreign class IRCContext { static nick() {} static target() {} static text() {} static command() {} static args() {} } class Bot { static hello(nick) { return \"Hello from WreC\" } static event(name,nick,target) { if (name == \"join\") { IRC.say(target, \"Welcome from WreC\"); return \"Welcome from WreC\"; } return null } static tick() { IRC.say(\"#test\", \"tick\"); } }";
int wren_backend_init(void){memset(timer_contexts,0,sizeof(timer_contexts));memset(event_bindings,0,sizeof(event_bindings));memset(command_bindings,0,sizeof(command_bindings));WrenConfiguration config;wrenInitConfiguration(&config);config.bindForeignMethodFn=bind_foreign;vm=wrenNewVM(&config);if(!vm)return -1;if(wrenInterpret(vm,"bot",bootstrap)!=WREN_RESULT_SUCCESS)return -1;hello_call=wrenMakeCallHandle(vm,"hello(_)");event_call=wrenMakeCallHandle(vm,"event(_,_,_)");return hello_call&&event_call?0:-1;}
void wren_backend_shutdown(void){if(vm&&hello_call)wrenReleaseHandle(vm,hello_call);if(vm&&event_call)wrenReleaseHandle(vm,event_call);if(vm)wrenFreeVM(vm);hello_call=NULL;event_call=NULL;vm=NULL;}
int wren_backend_command(const char *method,const irc_event *event,char *reply,size_t rs){const char *result;size_t i;if(!vm||!method||!event||!reply||!rs)return 0;active_event=*event;active_event_valid=1;for(i=0;i<WREC_COMMAND_MAX;i++)if(command_bindings[i].active&&strcmp(command_bindings[i].name,method)==0){WrenHandle *call;wrenEnsureSlots(vm,1);wrenGetVariable(vm,"bot","Bot",0);call=wrenMakeCallHandle(vm,command_bindings[i].handler);if(!call)return 0;if(wrenCall(vm,call)!=WREN_RESULT_SUCCESS){wrenReleaseHandle(vm,call);return 0;}wrenReleaseHandle(vm,call);if(wrenGetSlotType(vm,0)==WREN_TYPE_STRING){result=wrenGetSlotString(vm,0);snprintf(reply,rs,"%s",result);active_event_valid=0;return 1;}active_event_valid=0;return 0;}return 0;}
int wren_backend_event(const char *name,const irc_event *event,char *reply,size_t rs){const char *result;size_t i;if(!vm||!event||!name||!reply||!rs)return 0;for(i=0;i<8;i++)if(event_bindings[i].active&&strcmp(event_bindings[i].name,name)==0){WrenHandle *call;wrenEnsureSlots(vm,1);wrenGetVariable(vm,"bot","Bot",0);call=wrenMakeCallHandle(vm,event_bindings[i].handler);if(!call)return 0;if(wrenCall(vm,call)!=WREN_RESULT_SUCCESS){wrenReleaseHandle(vm,call);return 0;}wrenReleaseHandle(vm,call);if(wrenGetSlotType(vm,0)==WREN_TYPE_STRING){result=wrenGetSlotString(vm,0);snprintf(reply,rs,"%s",result);return 1;}return 0;}if(!event_call)return 0;wrenEnsureSlots(vm,4);wrenGetVariable(vm,"bot","Bot",0);wrenSetSlotString(vm,1,name);wrenSetSlotString(vm,2,event->nick);wrenSetSlotString(vm,3,event->target);if(wrenCall(vm,event_call)!=WREN_RESULT_SUCCESS)return 0;if(wrenGetSlotType(vm,0)!=WREN_TYPE_STRING)return 0;result=wrenGetSlotString(vm,0);snprintf(reply,rs,"%s",result);return 1;}
#else
void wren_backend_set_output_sink(const irc_output_sink *sink){(void)sink;}
int wren_backend_init(void){return -1;} void wren_backend_shutdown(void){}
int wren_backend_command(const char *m,const irc_event *e,char *r,size_t n){(void)m;(void)e;(void)r;(void)n;return 0;}
int wren_backend_event(const char *m,const irc_event *e,char *r,size_t n){(void)m;(void)e;(void)r;(void)n;return 0;}
#endif
